name: Java CI with Maven and S3 Upload

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    name: Build, Test, and Deploy
    runs-on: ubuntu-22.04
    permissions:
      id-token: write
      contents: read
      security-events: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      - name: Build with Maven
        run: ./mvnw clean package -Pproduction

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/tf_github_actions_role-${{ secrets.AWS_REGION }}
          audience: sts.amazonaws.com

      - name: Debug AWS config
        run: |
          aws sts get-caller-identity
          aws configure list

      - name: Get AWS Region
        run: |
          AWS_REGION=$(aws ssm get-parameter --name "/github-actions/region" --query "Parameter.Value" --output text)
          echo "AWS_REGION=$AWS_REGION" >> $GITHUB_ENV

      - name: Get S3 Bucket Name
        run: |
          S3_BUCKET_NAME=$(aws ssm get-parameter --name "/github-actions/s3-bucket-name" --query "Parameter.Value" --output text)
          echo "S3_BUCKET_NAME=$S3_BUCKET_NAME" >> $GITHUB_ENV

      - name: Upload artifact to S3 (Deploy)
        run: |
          aws s3 cp target/*.jar s3://${{ env.S3_BUCKET_NAME }}/application/jar/${{ secrets.JAR_FILE_NAME }}

      - name: Deployment Confirmation
        run: |
          echo "Artifact uploaded to S3 in region ${{ env.AWS_REGION }}. Deployment process initiated."
          echo "A Lambda function will trigger an SSM document to deploy the application."
